// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IBaseAdapter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IBaseAdapter";
  readonly sourceName: "contracts/interfaces/IBaseAdapter.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"bytes","name":"allocationData","type":"bytes"},{"internalType":"address","name":"liquidityMigrator","type":"address"}],"name":"allocateLiquidity","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"bytes","name":"protocolData","type":"bytes"},{"internalType":"address","name":"destinationAdapter","type":"address"}],"name":"extractLiquidity","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IBaseAdapter.sol";
  readonly buildInfoId: "solc-0_8_28-1e970f38cf8460bd356cbaf2dc22f6087274fdef";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IBaseAdapter"]: IBaseAdapter$Type;
    ["contracts/interfaces/IBaseAdapter.sol:IBaseAdapter"]: IBaseAdapter$Type;
  }
}