// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockEntropy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockEntropy";
  readonly sourceName: "contracts/tests/mocks/MockEntropy.sol";
  readonly abi: [{"inputs":[],"name":"requestV2","outputs":[{"internalType":"uint256","name":"requestId","type":"uint256"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5060af80601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c80637b43155d14602a575b5f5ffd5b60306044565b604051603b91906062565b60405180910390f35b5f6001905090565b5f819050919050565b605c81604c565b82525050565b5f60208201905060735f8301846055565b9291505056fea26469706673582212209a2a2c92aac6b5254eede525361d1a2fc7562abb1401b95e22ffc14aec5f9ff364736f6c634300081c0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106026575f3560e01c80637b43155d14602a575b5f5ffd5b60306044565b604051603b91906062565b60405180910390f35b5f6001905090565b5f819050919050565b605c81604c565b82525050565b5f60208201905060735f8301846055565b9291505056fea26469706673582212209a2a2c92aac6b5254eede525361d1a2fc7562abb1401b95e22ffc14aec5f9ff364736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/tests/mocks/MockEntropy.sol";
  readonly buildInfoId: "solc-0_8_28-1e970f38cf8460bd356cbaf2dc22f6087274fdef";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockEntropy"]: MockEntropy$Type;
    ["contracts/tests/mocks/MockEntropy.sol:MockEntropy"]: MockEntropy$Type;
  }
}